# Dockerfile for running goss tests.
#
# Required due to bay php.ini config set up during ONBUILD.

ARG BASE_IMAGE
FROM ${BASE_IMAGE}
LABEL org.opencontainers.image.source="https://github.com/dpc-sdp/bay/blob/5.x/images/bay-php_goss/Dockerfile"