ARG PHP_VERSION=8.3
FROM php:${PHP_VERSION}-cli-alpine AS php-cli
FROM ghcr.io/skpr/mtk:v2.1.0 AS mtk
FROM uselagoon/php-${PHP_VERSION}-cli-drupal:latest

# Remove unnecessary packages that increase our attack surface area.
RUN apk del postgresql-client

ARG GOJQ_VERSION=0.12.17
ARG DOCKERIZE_VERSION=v0.9.2
ARG BAY_CLI_VERSION=v1.3.2
ARG SHIPSHAPE_VERSION=1.0.0-alpha.1.5.1

COPY --from=php-cli /usr/local/bin/phpdbg /usr/local/bin/
ENV WEBROOT=docroot
ENV COMPOSER_CACHE_DIR=/tmp/.composer/cache

# Install gojq.
RUN curl -L https://github.com/itchyny/gojq/releases/download/v${GOJQ_VERSION}/gojq_v${GOJQ_VERSION}_linux_amd64.tar.gz --output /tmp/gojq_v${GOJQ_VERSION}_linux_amd64.tar.gz && \
    tar -C /tmp -xvf /tmp/gojq_v${GOJQ_VERSION}_linux_amd64.tar.gz && \
    chmod +x /tmp/gojq_v${GOJQ_VERSION}_linux_amd64/gojq && \
    mv /tmp/gojq_v${GOJQ_VERSION}_linux_amd64/gojq /usr/local/bin

RUN wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin && \ 
    chmod +x /usr/local/bin/dockerize

# Install redis-cli for debugging.
RUN apk add redis --no-cache

# Install bay-cli.
RUN curl -L "https://github.com/dpc-sdp/bay-cli/releases/download/${BAY_CLI_VERSION}/bay_$(echo ${TARGETPLATFORM:-linux/amd64} | tr '/' '_').tar.gz" --output /tmp/bay_$(echo ${TARGETPLATFORM:-linux/amd64} | tr '/' '_').tar.gz
RUN tar -C /tmp -xvf /tmp/bay_$(echo ${TARGETPLATFORM:-linux/amd64} | tr '/' '_').tar.gz
RUN chmod +x /tmp/bay
RUN mv /tmp/bay /bin/bay

RUN mkdir /bay

COPY 01-bay.ini /usr/local/etc/php/conf.d/
COPY bay-php-config.sh /bay

# Install shipshape
RUN curl -L -o /usr/local/bin/shipshape https://github.com/salsadigitalauorg/shipshape/releases/download/v${SHIPSHAPE_VERSION}/shipshape-$(uname -s)-$(uname -m) && \
    chmod +x /usr/local/bin/shipshape

# Bay entrypoints.
COPY entrypoints/ /lagoon/entrypoints

# Add common drupal config.
COPY redis-unavailable.services.yml /bay
COPY redis-cluster.services.yml /bay
COPY redis-single.services.yml /bay
COPY settings.php /bay
COPY log-fatals.php /bay
COPY db-build.sh /bay
COPY db-dump-sanitized.sh /bay
COPY mtk /bay/mtk
COPY drush.yml /home/.drush/drush.yml

# Provide a separate environment variable to configure the php cli memory limit.
ENV PHP_CLI_MEMORY_LIMIT=1024M
RUN sed -i 's/\${PHP_MEMORY_LIMIT:/\${PHP_CLI_MEMORY_LIMIT:/g' "$PHP_INI_DIR/conf.d/00-lagoon-php.ini.tpl"

ARG TZ=Australia/Melbourne
RUN  apk add --no-cache tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone

# mtk for dev db snapshots
COPY --from=mtk /usr/local/bin/mtk /usr/local/bin

# aws cli for pushing db snapshots to s3.
RUN  apk add --no-cache aws-cli

ONBUILD ARG MTK_CONFIG=/bay/mtk/drupal.conf
ONBUILD ARG BAY_DISABLE_FUNCTIONS=phpinfo,pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,system,exec,shell_exec,passthru,phpinfo,show_source,highlight_file,popen,fopen_with_path,dbmopen,dbase_open,filepro,filepro_rowcount,filepro_retrieve,posix_mkfifo
ONBUILD ARG BAY_UPLOAD_LIMIT=100M
ONBUILD ARG BAY_POST_MAX=100M
ONBUILD ARG BAY_SESSION_NAME=PHPSESSID
ONBUILD ARG BAY_SESSION_COOKIE_LIFETIME=28800
ONBUILD ARG BAY_SESSION_STRICT=1
ONBUILD ARG BAY_SESSION_SID_LEN=256
ONBUILD ARG BAY_SESSION_SID_BITS=6

ONBUILD ENV MTK_CONFIG $MTK_CONFIG
ONBUILD ENV BAY_DISABLE_FUNCTIONS $BAY_DISABLE_FUNCTIONS
ONBUILD ENV BAY_UPLOAD_LIMIT $BAY_UPLOAD_LIMIT
ONBUILD ENV BAY_POST_MAX $BAY_POST_MAX
ONBUILD ENV BAY_SESSION_NAME $BAY_SESSION_NAME
ONBUILD ENV BAY_SESSION_COOKIE_LIFETIME $BAY_SESSION_COOKIE_LIFETIME
ONBUILD ENV BAY_SESSION_STRICT $BAY_SESSION_STRICT
ONBUILD ENV BAY_SESSION_SID_LEN $BAY_SESSION_SID_LEN
ONBUILD ENV BAY_SESSION_SID_BITS $BAY_SESSION_SID_BITS

ONBUILD RUN /bay/bay-php-config.sh
