---
collections:
  - ansible.posix
  - ansible.utils
  - community.general
  - community.elastic
  - kubernetes.core
  - name: lagoon.api
    source: https://github.com/salsadigitalauorg/lagoon_ansible_collection.git
    version: master
    type: git
  - name: section.api
    source: https://github.com/salsadigitalauorg/section_ansible_collection.git
    version: main
    type: git
