---
collections:
  - ansible.posix
  - ansible.utils
  - community.general
  - kubernetes.core
  - git+https://github.com/salsadigitalauorg/lagoon_ansible_collection.git,master
  - git+https://github.com/salsadigitalauorg/section_ansible_collection.git,main
