---
collections:
  - ansible.posix
  - ansible.utils
  - awx.awx
  - community.general
  - kubernetes.core
  - name: lagoon.api
    source: https://github.com/salsadigitalauorg/lagoon_ansible_collection.git
    version: feature/DEVOPS-71-deploy-targets
    type: git
  - name: section.api
    source: https://github.com/salsadigitalauorg/section_ansible_collection.git
    version: main
    type: git
