---
collections:
  - ansible.posix
  - ansible.utils
  - awx.awx
  - name: community.general
    version: "11.1.2"
  - kubernetes.core
  - name: lagoon.api
    source: https://github.com/GROwen/lagoon_ansible_collection.git
    version: patch-1
    type: git
  - name: section.api
    source: https://github.com/salsadigitalauorg/section_ansible_collection.git
    version: main
    type: git
