---
collections:
  - ansible.posix
  - ansible.utils
  - awx.awx
  - community.general
  - kubernetes.core
  - name: https://github.com/salsadigitalauorg/lagoon_ansible_collection.git
    version: master
    type: git
  - name: https://github.com/salsadigitalauorg/section_ansible_collection.git
    version: main
    type: git
