name: build-deploy-bay-images
run-name: Build and deploy Bay images
on:
  pull_request:
    types:
      - closed
      - opened
      - synchronize
  schedule:
    - cron: '23 20 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
jobs:
  buildx:
    if: github.event.pull_request.merged == true || contains(fromJson('["schedule", "workflow_dispatch"]'), github.event_name) || github.event_name == 'pull_request' && startsWith(github.head_ref,'build/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images: ${{ fromJson(vars.IMAGES) }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.images }}
          tags: |
            type=ref,event=pr,enable=${{ github.event.pull_request.merged == false }}
            type=raw,value=${{ github.event.pull_request.base.ref }},enable=${{ github.event.pull_request.merged == true }}
            type=ref,event=branch,enable=${{ contains(fromJson('["schedule", "workflow_dispatch"]'), github.event_name) }}
          labels: |
            maintainer=Digital Victoria
            repository=${{ github.repositoryUrl }}
            org.opencontainers.image.authors=Digital Victoria
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/${{ (contains(fromJson('["opened","synchronize"]'), github.event.action)) && github.head_ref || github.event.action == 'closed' && github.base_ref || github.ref_name }}/images/${{ matrix.images }}/Dockerfile
            org.opencontainers.image.title=${{ matrix.images }}
            org.opencontainers.image.description=${{ matrix.images }} image for Bay container platform
          annotations: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/${{ (contains(fromJson('["opened","synchronize"]'), github.event.action)) && github.head_ref || github.event.action == 'closed' && github.base_ref || github.ref_name }}/images/${{ matrix.images }}/Dockerfile

      - name: Build and push the images
        uses: docker/bake-action@v3.1.0
        with:
          push: true
          files: |
            ./gh-actions-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
            ${{ steps.meta.outputs.bake-file-annotations }}
          # Target the default group - probably unnecessary.
          targets: ${{ matrix.images }}
