name: build-deploy-bay-awx-ee
run-name: Build and deploy Bay AWX Execution Environment
on:
  pull_request:
    types:
      - closed
      - opened
      - synchronize
  schedule:
    - cron: '23 20 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
jobs:
  buildx:
    if: github.event.pull_request.merged == true || contains(fromJson('["schedule", "workflow_dispatch"]'), github.event_name) || github.event_name == 'pull_request' && startsWith(github.head_ref,'build/')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./images/awx-ee
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}


      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/awx-ee
          tags: |
            type=ref,event=pr,enable=${{ github.event.pull_request.merged == false }}
            type=raw,value=${{ github.event.pull_request.base.ref }},enable=${{ github.event.pull_request.merged == true }}
            type=ref,event=branch,enable=${{ contains(fromJson('["schedule", "workflow_dispatch"]'), github.event_name) }}

      - name: Create context and build instruction file
        run: |
          pip install --upgrade ansible-builder
          ansible-builder build \
            --container-runtime docker \
            --tag ${{ steps.meta.outputs.tags }} \
            --build-arg PKGMGR="/usr/bin/apt-get" \
            --build-arg PYCMD="/usr/local/bin/python3" \
            --verbosity 3


      # Refactored to use bake but it's substantially slower so we'll do a push instead
      # see https://github.com/docker/build-push-action/issues/538#issuecomment-1869681934
      # However this approach may be at the cost of multi-arch support.
      - name: Test
        run: |
          docker images

      - name: Push
        run: |
          docker push --all-tags ${{ env.REGISTRY }}/${{ github.repository }}/awx-ee


      # - name: Build and push the AWX-EE image
      #   uses: docker/bake-action@v4
      #   with:
      #     push: true
      #     workdir: ./images/awx-ee
      #     files: |
      #       ./docker-bake.hcl
      #       ${{ steps.meta.outputs.bake-file }}
