name: build-deploy-bay-images
run-name: Build and deploy Bay images
on: [push]
jobs:
  buildx:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: docker buildx inspect
