name: build-deploy-bay-images
run-name: Build and deploy Bay images
on:
  push
env:
  REGISTRY: ghcr.io
#defaults:
#  run:
#    working-directory: ${{ github.workspace }}
jobs:
  build-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      #  images: [ci-builder, php-cli, mariadb, nginx, node, php-fpm, elasticsearch, mailhog, clamav, ripple-static]
        images: [ci-builder, php-cli]
    needs: build-setup
    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.images }}
          bake-target: docker-metadata-${{ matrix.images }}
          tags: |
            type=ref,event=branch

      - name: Build and push the images
        uses: docker/bake-action@v3.1.0
        with:
          workdir: ${{ github.workspace }}
          files: |
            ./gh-actions-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          # Target the default group - probably unnecessary.
          targets: ${{ matrix.images }}