name: clair-scan
run-name: Scan published images using Clair.
env:
  REGISTRY: ghcr.io
on: push
  # registry_package:
  #   types:
  #     - "published"
  # schedule:
  #   - cron: '0 0 * * 4'

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images: [nginx, node]
        tags: [5.x]
    steps:
      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.images }}:${{matrix.tags}}
          dockerfile: ./images/${{ matrix.images }}
      - name: Upload SARIF file
        if: ${{ steps.scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
