name: vulnerability-scan
run-name: Scan published images for vulnerabilities.
env:
  REGISTRY: ghcr.io
on: push
  # registry_package:
  #   types:
  #     - "published"
  # schedule:
  #   - cron: '0 0 * * 4'

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        images: ${{ fromJson(vars.IMAGES) }}
        branches: ${{ fromJson(vars.BRANCHES) }}
    steps:
      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.images }}:${{matrix.branches}}
          dockerfile: ./images/${{ matrix.images }}
      - name: Upload SARIF file
        if: ${{ steps.scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
