---
collections:
  - ansible.posix
  - ansible.utils
  - community.general
  - kubernetes.core
  - name: lagoon.api
    source: https://github.com/salsadigitalauorg/lagoon_ansible_collection.git
    version: master
    type: git
